<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{Most probably asked questions}
-->

Most Probably Asked Questions
=================================================

**Author**: Zuguang Gu ( z.gu@dkfz.de )

**Date**: `r Sys.Date()`

**Package version**: `r installed.packages()["ComplexHeatmap", "Version"]`

---------------------------------------

```{r, echo = FALSE, message = FALSE}
library(markdown)
options(markdown.HTML.options = c(options('markdown.HTML.options')[[1]], "toc"))
library(knitr)
knitr::opts_chunk$set(
    error = FALSE,
    tidy  = FALSE,
    message = FALSE,
    fig.align = "center",
    fig.width = 6,
    fig.height = 6)
options(markdown.HTML.stylesheet = "custom.css")
options(width = 100)
```

## There is no plot comming out after running `Heatmap()` function.

In this case, you need to use `draw()` function explicitly. See https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#plot-the-heatmap.

## Retrieve orders and dendrograms.

For retrieving orders and dendrograms from a single heatmap, see https://jokergoo.github.io/ComplexHeatmap-reference/book/a-single-heatmap.html#get-orders-and-dendrograms-from-heatmap.

For retrieving orders and dendrograms from a list of heatmaps, see https://jokergoo.github.io/ComplexHeatmap-reference/book/a-list-of-heatmaps.html#get-orders-and-dendrograms

## How to control the style of legends.

The style of legends can be controlled by `heatmap_legend_param` in `Heatmap()`, or
`annotation_legend_param` in `HeatmapAnnotation()`. The parameters for controlling legends are those
arguments in `Legend()` function, see
https://jokergoo.github.io/ComplexHeatmap-reference/book/legends.html#heatmap-and-annotation-legends.

## Some text are cut by the plotting region

The layout of the **ComplexHeatmap** is not perfect that it is still possible some of the text are
drawn out of the plotting region. In this case, you set the `padding` argument in `draw()` function
to increase the blank areas around the final plot.

## Can the heatmaps be added vertically?

Yes, use `%v%` instead of `+`.

## Does Heatmap titles supports mathematical expression?

Yes, all the text-related elements (e.g. titles, row names, legend titles, legend labels, ...) allow
methematical expression.

## I have many heatmaps and I want to them into panels for a big figure for my paper.

You can set `newpage = FALSE` in `draw()` function and use `grid.layout()` to manage the layout of
your panels. But I suggest more to use `grid.grabExpr()` to directly capture the output of the
heatmap and later draw the whole plot as a single graphic element by `grid.draw()`.
 