<!-- Generated by pkgdown: do not edit by hand -->
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>Draw Legend Based on Color Mapping — color_mapping_legend-ColorMapping-method • ComplexHeatmap</title>

<!-- jquery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<!-- Bootstrap -->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script>

<!-- Font Awesome icons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/all.min.css" integrity="sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/v4-shims.min.css" integrity="sha256-6qHlizsOWFskGlwVOKuns+D1nB6ssZrHQrNj1wGplHc=" crossorigin="anonymous" />

<!-- clipboard.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script>

<!-- headroom.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/headroom.min.js" integrity="sha256-DJFC1kqIhelURkuza0AvYal5RxMtpzLjFhsnVIeuk+U=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script>

<!-- pkgdown -->
<link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script>



<meta property="og:title" content="Draw Legend Based on Color Mapping — color_mapping_legend-ColorMapping-method" />

<meta property="og:description" content="Draw Legend Based on Color Mapping" />
<meta name="twitter:card" content="summary" />



<!-- mathjax -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script>

<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->



  </head>

  <body>
    <div class="container template-reference-topic">
      <header>
      <div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">ComplexHeatmap</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">2.1.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="../articles/complex_heatmap.html">UNKNOWN TITLE</a>
    </li>
    <li>
      <a href="../articles/most_probably_asked_questions.html">UNKNOWN TITLE</a>
    </li>
  </ul>
</li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/jokergoo/ComplexHeatmap">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
      
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

      

      </header>

<div class="row">
  <div class="col-md-9 contents">
    <div class="page-header">
    <h1>Draw Legend Based on Color Mapping</h1>
    
    <div class="hidden name"><code>color_mapping_legend-ColorMapping-method.rd</code></div>
    </div>

    <div class="ref-description">
    
    <p>Draw Legend Based on Color Mapping</p>
    
    </div>

    <pre class="usage"><span class='co'># S4 method for ColorMapping</span>
<span class='fu'><a href='color_mapping_legend-ColorMapping-method.rd.html'>color_mapping_legend</a></span>(<span class='no'>object</span>,
    <span class='kw'>plot</span> <span class='kw'>=</span> <span class='fl'>TRUE</span>, <span class='no'>...</span>,

    <span class='kw'>color_bar</span> <span class='kw'>=</span> <span class='no'>object</span>@<span class='kw'>type</span>,

    <span class='kw'>title</span> <span class='kw'>=</span> <span class='no'>object</span>@<span class='kw'>name</span>,
    <span class='kw'>title_gp</span> <span class='kw'>=</span> <span class='fu'>gpar</span>(<span class='kw'>fontsize</span> <span class='kw'>=</span> <span class='fl'>10</span>, <span class='kw'>fontface</span> <span class='kw'>=</span> <span class='st'>"bold"</span>),
    <span class='kw'>title_position</span> <span class='kw'>=</span> <span class='st'>"topleft"</span>,
    <span class='kw'>grid_height</span> <span class='kw'>=</span> <span class='fu'>unit</span>(<span class='fl'>4</span>, <span class='st'>"mm"</span>),
    <span class='kw'>grid_width</span> <span class='kw'>=</span> <span class='fu'>unit</span>(<span class='fl'>4</span>, <span class='st'>"mm"</span>),
    <span class='kw'>border</span> <span class='kw'>=</span> <span class='kw'>NULL</span>,
    <span class='kw'>at</span> <span class='kw'>=</span> <span class='no'>object</span>@<span class='kw'>levels</span>,
    <span class='kw'>labels</span> <span class='kw'>=</span> <span class='no'>at</span>,
    <span class='kw'>labels_gp</span> <span class='kw'>=</span> <span class='fu'>gpar</span>(<span class='kw'>fontsize</span> <span class='kw'>=</span> <span class='fl'>10</span>),
    <span class='kw'>labels_rot</span> <span class='kw'>=</span> <span class='fl'>0</span>,
    <span class='kw'>nrow</span> <span class='kw'>=</span> <span class='kw'>NULL</span>,
    <span class='kw'>ncol</span> <span class='kw'>=</span> <span class='fl'>1</span>,
    <span class='kw'>by_row</span> <span class='kw'>=</span> <span class='fl'>FALSE</span>,
    <span class='kw'>legend_height</span> <span class='kw'>=</span> <span class='kw'>NULL</span>,
    <span class='kw'>legend_width</span> <span class='kw'>=</span> <span class='kw'>NULL</span>,
    <span class='kw'>legend_direction</span> <span class='kw'>=</span> <span class='fu'><a href='https://rdrr.io/r/base/c.html'>c</a></span>(<span class='st'>"vertical"</span>, <span class='st'>"horizontal"</span>),

    <span class='kw'>param</span> <span class='kw'>=</span> <span class='kw'>NULL</span>)</pre>
    
    <h2 class="hasAnchor" id="arguments"><a class="anchor" href="#arguments"></a>Arguments</h2>
    <table class="ref-arguments">
    <colgroup><col class="name" /><col class="desc" /></colgroup>
    <tr>
      <th>object</th>
      <td><p>A <code><a href='ColorMapping-class.rd.html'>ColorMapping-class</a></code> object.</p></td>
    </tr>
    <tr>
      <th>plot</th>
      <td><p>Whether to plot or just return the legend object?</p></td>
    </tr>
    <tr>
      <th>...</th>
      <td><p>Pass to <code><a href='draw-Legends-method.rd.html'>draw,Legends-method</a></code>.</p></td>
    </tr>
    <tr>
      <th>color_bar</th>
      <td><p>"continous" or "discrete". It controls whether to show the discrete legend for the continuous color mapping.</p></td>
    </tr>
    <tr>
      <th>title</th>
      <td><p>Title of the legend, by default it is the name of the legend.</p></td>
    </tr>
    <tr>
      <th>title_gp</th>
      <td><p>Graphical parameters for legend title.</p></td>
    </tr>
    <tr>
      <th>title_position</th>
      <td><p>Position of the title. See <code><a href='Legend.rd.html'>Legend</a></code> for all possible values.</p></td>
    </tr>
    <tr>
      <th>grid_height</th>
      <td><p>Height of each legend grid. Pass to <code><a href='Legend.rd.html'>Legend</a></code>.</p></td>
    </tr>
    <tr>
      <th>grid_width</th>
      <td><p>Width of each legend grid. Pass to <code><a href='Legend.rd.html'>Legend</a></code>.</p></td>
    </tr>
    <tr>
      <th>border</th>
      <td><p>Color for legend grid borders. Pass to <code><a href='Legend.rd.html'>Legend</a></code>.</p></td>
    </tr>
    <tr>
      <th>at</th>
      <td><p>Break values of the legend. By default it is the levels in the <code><a href='ColorMapping-class.rd.html'>ColorMapping-class</a></code> object.</p></td>
    </tr>
    <tr>
      <th>labels</th>
      <td><p>Labels corresponding to break values.</p></td>
    </tr>
    <tr>
      <th>labels_gp</th>
      <td><p>Graphcial parameters for legend labels.</p></td>
    </tr>
    <tr>
      <th>labels_rot</th>
      <td><p>Rotation of labels.</p></td>
    </tr>
    <tr>
      <th>nrow</th>
      <td><p>Pass to <code><a href='Legend.rd.html'>Legend</a></code>. It controls the layout of legend grids if they are arranged in multiple rows or columns.</p></td>
    </tr>
    <tr>
      <th>ncol</th>
      <td><p>Pass to <code><a href='Legend.rd.html'>Legend</a></code>. It controls the layout of legend grids if they are arranged in multiple rows or columns.</p></td>
    </tr>
    <tr>
      <th>by_row</th>
      <td><p>Pass to <code><a href='Legend.rd.html'>Legend</a></code>. It controls the order of legend grids if they are arranged in multiple rows or columns.</p></td>
    </tr>
    <tr>
      <th>legend_height</th>
      <td><p>Height of the legend body. It only works when <code>color_bar</code> is <code>continuous</code> and <code>direction</code> is <code>vertical</code>. Pass to <code><a href='Legend.rd.html'>Legend</a></code>.</p></td>
    </tr>
    <tr>
      <th>legend_width</th>
      <td><p>Width of the legend body. It only works when <code>color_bar</code> is <code>continuous</code> and <code>direction</code> is <code>horizontal</code>. Pass to <code><a href='Legend.rd.html'>Legend</a></code>.</p></td>
    </tr>
    <tr>
      <th>legend_direction</th>
      <td><p>When <code>color_bar</code> is <code>continuous</code>, whether the legend is vertical or horizontal? Pass to <code><a href='Legend.rd.html'>Legend</a></code>.</p></td>
    </tr>
    <tr>
      <th>param</th>
      <td><p>All the legend-related parameters can be specified as a single list.</p></td>
    </tr>
    </table>
    
    <h2 class="hasAnchor" id="details"><a class="anchor" href="#details"></a>Details</h2>

    <p>The legend is constructed by <code><a href='Legend.rd.html'>Legend</a></code>.</p>
    
    <h2 class="hasAnchor" id="value"><a class="anchor" href="#value"></a>Value</h2>

    <p>A <code><a href='Legends-class.rd.html'>Legends-class</a></code> object.</p>
    

    <h2 class="hasAnchor" id="examples"><a class="anchor" href="#examples"></a>Examples</h2>
    <pre class="examples"><div class='input'><span class='co'># There is no example</span>
<span class='kw'>NULL</span></div><div class='output co'>#&gt; NULL</div><div class='input'>
</div></pre>
  </div>
  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
    <h2>Contents</h2>
    <ul class="nav nav-pills nav-stacked">
      <li><a href="#arguments">Arguments</a></li>
      
      <li><a href="#details">Details</a></li>

      <li><a href="#value">Value</a></li>
      
      <li><a href="#examples">Examples</a></li>
    </ul>

    <h2>Author</h2>
    <p>Zuguang Gu &lt;z.gu@dkfz.de&gt;</p>
  </div>
</div>


      <footer>
      <div class="copyright">
  <p>Developed by Zuguang Gu.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.4.1.</p>
</div>

      </footer>
   </div>

  


  </body>
</html>


