<!-- Generated by pkgdown: do not edit by hand -->
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>Resize the Width or Height of Heatmap Annotations — re_size-HeatmapAnnotation-method • ComplexHeatmap</title>

<!-- jquery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<!-- Bootstrap -->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script>

<!-- Font Awesome icons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/all.min.css" integrity="sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/v4-shims.min.css" integrity="sha256-6qHlizsOWFskGlwVOKuns+D1nB6ssZrHQrNj1wGplHc=" crossorigin="anonymous" />

<!-- clipboard.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script>

<!-- headroom.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/headroom.min.js" integrity="sha256-DJFC1kqIhelURkuza0AvYal5RxMtpzLjFhsnVIeuk+U=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script>

<!-- pkgdown -->
<link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script>



<meta property="og:title" content="Resize the Width or Height of Heatmap Annotations — re_size-HeatmapAnnotation-method" />

<meta property="og:description" content="Resize the Width or Height of Heatmap Annotations" />
<meta name="twitter:card" content="summary" />



<!-- mathjax -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script>

<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->



  </head>

  <body>
    <div class="container template-reference-topic">
      <header>
      <div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">ComplexHeatmap</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">2.1.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="../articles/complex_heatmap.html">UNKNOWN TITLE</a>
    </li>
    <li>
      <a href="../articles/most_probably_asked_questions.html">UNKNOWN TITLE</a>
    </li>
  </ul>
</li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/jokergoo/ComplexHeatmap">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
      
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

      

      </header>

<div class="row">
  <div class="col-md-9 contents">
    <div class="page-header">
    <h1>Resize the Width or Height of Heatmap Annotations</h1>
    
    <div class="hidden name"><code>re_size-HeatmapAnnotation-method.rd</code></div>
    </div>

    <div class="ref-description">
    
    <p>Resize the Width or Height of Heatmap Annotations</p>
    
    </div>

    <pre class="usage"><span class='co'># S4 method for HeatmapAnnotation</span>
<span class='fu'><a href='re_size-HeatmapAnnotation-method.rd.html'>re_size</a></span>(<span class='no'>object</span>,
    <span class='kw'>annotation_height</span> <span class='kw'>=</span> <span class='kw'>NULL</span>,
    <span class='kw'>annotation_width</span> <span class='kw'>=</span> <span class='kw'>NULL</span>,
    <span class='kw'>height</span> <span class='kw'>=</span> <span class='kw'>NULL</span>,
    <span class='kw'>width</span> <span class='kw'>=</span> <span class='kw'>NULL</span>,
    <span class='kw'>simple_anno_size</span> <span class='kw'>=</span> <span class='no'>object</span>@<span class='kw'>param</span>$<span class='no'>simple_anno_size</span>,
    <span class='kw'>simple_anno_size_adjust</span> <span class='kw'>=</span> <span class='no'>object</span>@<span class='kw'>param</span>$<span class='no'>simple_anno_size_adjust</span>)</pre>
    
    <h2 class="hasAnchor" id="arguments"><a class="anchor" href="#arguments"></a>Arguments</h2>
    <table class="ref-arguments">
    <colgroup><col class="name" /><col class="desc" /></colgroup>
    <tr>
      <th>object</th>
      <td><p>A <code><a href='HeatmapAnnotation-class.rd.html'>HeatmapAnnotation-class</a></code> object.</p></td>
    </tr>
    <tr>
      <th>annotation_height</th>
      <td><p>A vector of of annotation heights in <code><a href='https://rdrr.io/r/grid/unit.html'>unit</a></code> class.</p></td>
    </tr>
    <tr>
      <th>annotation_width</th>
      <td><p>A vector of of annotation widths in <code><a href='https://rdrr.io/r/grid/unit.html'>unit</a></code> class.</p></td>
    </tr>
    <tr>
      <th>height</th>
      <td><p>The height of the complete heatmap annotation.</p></td>
    </tr>
    <tr>
      <th>width</th>
      <td><p>The width of the complete heatmap annotation.</p></td>
    </tr>
    <tr>
      <th>simple_anno_size</th>
      <td><p>The size of one line of the simple annotation.</p></td>
    </tr>
    <tr>
      <th>simple_anno_size_adjust</th>
      <td><p>Whether adjust the size of the simple annotation?</p></td>
    </tr>
    </table>
    
    <h2 class="hasAnchor" id="details"><a class="anchor" href="#details"></a>Details</h2>

    <p>The function only adjust height for column annotations and width for row annotations.</p>
<p>The basic rules are (take <code>height</code> and <code>annotation_height</code> for example:</p>
<p>1. If <code>annotation_height</code> is set and all
   <code>annotation_height</code> are absolute units, <code>height</code> is ignored.
2. If <code>annotation_height</code> contains non-absolute units, <code>height</code> also need to be set and the
   non-absolute units should be set in a simple form such as 1:10 or <code>unit(1, "null")</code>.
3. <code>simple_anno_size</code> is only used when <code>annotation_height</code> is NULL.
4. If only <code>height</code> is set, non-simple annotation is adjusted while keeps simple anntation unchanged.
5. If only <code>height</code> is set and all annotations are simple annotations, all anntations are adjusted,
     and <code>simple_anno_size</code> is disabled.
6. If <code>simple_anno_size_adjust</code> is <code>FALSE</code>, the size of the simple annotations will not change.</p>
    

    <h2 class="hasAnchor" id="examples"><a class="anchor" href="#examples"></a>Examples</h2>
    <pre class="examples"><div class='input'><span class='co'># There is no example</span>
<span class='kw'>NULL</span></div><div class='output co'>#&gt; NULL</div><div class='input'>
</div></pre>
  </div>
  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
    <h2>Contents</h2>
    <ul class="nav nav-pills nav-stacked">
      <li><a href="#arguments">Arguments</a></li>
      
      <li><a href="#details">Details</a></li>
      
      <li><a href="#examples">Examples</a></li>
    </ul>

  </div>
</div>


      <footer>
      <div class="copyright">
  <p>Developed by Zuguang Gu.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.4.1.</p>
</div>

      </footer>
   </div>

  


  </body>
</html>


